version: "3.1"


services:
    rabbitmq:
      image: rabbitmq:3.12.8-management
      hostname: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"

      env_file: service.env

    server:
      build:
        dockerfile: src/Dockerfile
      ports:
        - "20000-20001:20000-20001"
      command: python3 main.py
