version: "3.1"


services:
    rabbitmq:
      image: rabbitmq:3.12.8-management
      ports:
        - "15672:15672"
      environment:
        -RABBITMQ_USER: $RABBITMQ_USER
        -RABBITMQ_PASS_FILE: $RABBITMQ_PASS_FILE
    server:
      build:
        dockerfile: src/Dockerfile
      ports:
        - "20000-20001:20000-20001"
      command: python3 main.py
